siteName: Mathias Bourgeois pro
productionUrl: https://poko-website-builder-erz.pages.dev/
languages:
  - code: fr
    name: Français
    customUrlPrefix:
      prefix: ''
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
