siteName: Mathias Bourgeois pro
productionUrl: poko-website-builder-erz.pages.dev
languages:
  - code: fr
    name: Français
    customUrlPrefix: null
    status: published
    isCmsDefault: false
    isWebsiteDefault: false
